# Documentation: https://sourcethemes.com/academic/
#
# toml syntax: https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Site title, upper left title bar
title = "CORIANNE BAKER"

# site URL
baseurl = "https://www.corianne.io/"

# copyright in footer. copyright symbol: &copy; 
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; 1980s-2019"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Comments section
disqusShortname = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
  theme = "hugo-academic"

# last modified date from git.
  enableGitInfo = false

# Default language to use multilingual. i don't have multilingual, set to 
  defaultContentLanguage = "en"
  hasCJKLanguage = false 
  defaultContentLanguageInSubdir = false
  
  paginate = 10  # Number of items per page in paginated lists.
  enableEmoji = true
  footnotereturnlinkcontents = "<sup>^</sup>"
  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
#  home = [ "HTML", "RSS", "JSON" ]
#  section = [ "HTML", "RSS" ]
#  below is from Alison Presmanes Hill 
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]
  taxonomy = [ "HTML", "RSS" ]
  taxonomyTerm = [ "HTML", "RSS" ]


# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
  angledQuotes = false
  latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
#  author = "authors"